# Generated by Django 5.2.14 on 2026-05-29 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="STARTER",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("ANNUAL", "Annual")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                (
                    "enabled_modules",
                    models.JSONField(
                        default=list, help_text="List of enabled module codes"
                    ),
                ),
                ("current_period_start", models.DateField()),
                ("current_period_end", models.DateField()),
                ("is_trial", models.BooleanField(default=True)),
                ("max_employees", models.PositiveIntegerField(default=50)),
                ("max_storage_gb", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
    ]
