import { LEAVE_MASTER_CATEGORY } from "../leave";
import { BASE_FIELDS, COMPANY_FIELDS, makeCategory } from "./helpers";
import { BRANCH_FIELDS, COMPANY_EXTRA_FIELDS } from "./fieldPresets";
import type { MasterCategoryConfig, MasterFieldConfig, MasterTableColumnConfig } from "../types";

const companyScoped = { companyScoped: true, formFields: COMPANY_FIELDS };

const nameBaseFields: MasterFieldConfig[] = [
  { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter code", section: "Basic Details" },
  { key: "name", label: "Name", type: "text", required: true, placeholder: "Enter name", section: "Basic Details" },
  { key: "is_active", label: "Active", type: "boolean", section: "Status" },
];

const labelBaseFields: MasterFieldConfig[] = [
  { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter code", section: "Basic Details" },
  { key: "label", label: "Label", type: "text", required: true, placeholder: "Enter label", section: "Basic Details" },
  { key: "is_active", label: "Active", type: "boolean", section: "Status" },
];

const companyNameBaseFields: MasterFieldConfig[] = [
  { key: "company", label: "Company", type: "select", relationMaster: "Company", required: true, section: "Company" },
  ...nameBaseFields,
];

const rangeBaseFields: MasterFieldConfig[] = [
  { key: "code", label: "Code", type: "text", placeholder: "Optional code", section: "Basic Details" },
  { key: "label", label: "Label", type: "text", required: true, placeholder: "Enter label", section: "Basic Details" },
  { key: "min_months", label: "Minimum Months", type: "number", required: true, min: 0, section: "Range" },
  { key: "max_months", label: "Maximum Months", type: "number", min: 0, section: "Range" },
  { key: "is_active", label: "Active", type: "boolean", section: "Status" },
];

const sortOrderField: MasterFieldConfig = {
  key: "sort_order",
  label: "Sort Order",
  type: "number",
  defaultValue: 0,
  min: 0,
  section: "Display",
};

const companyAuditColumns: Array<string | MasterTableColumnConfig> = [
  "code",
  { key: "name", label: "Name", altKeys: ["label"] },
  { key: "is_active", label: "Active", render: "status" },
];

const filterTypeOptions = [
  { value: "STATIC", label: "Static" },
  { value: "DYNAMIC", label: "Dynamic" },
];

const positionChangeTypeOptions = [
  { value: "PROMOTION", label: "Promotion" },
  { value: "TRANSFER", label: "Transfer" },
  { value: "CORRECTION", label: "Correction" },
  { value: "RESTRUCTURE", label: "Restructure" },
  { value: "DEMOTION", label: "Demotion" },
];

const documentSideOptions = [
  { value: "FULL", label: "Full" },
  { value: "FRONT", label: "Front" },
  { value: "BACK", label: "Back" },
  { value: "BOTH", label: "Both" },
];

const boardTypeOptions = [
  { value: "BOARD", label: "Board" },
  { value: "UNIVERSITY", label: "University" },
  { value: "INSTITUTE", label: "Institute" },
  { value: "OTHER", label: "Other" },
];

export const MASTER_CATEGORIES: MasterCategoryConfig[] = [
  makeCategory(
    "employee",
    "Employee Masters",
    [
      "Gender",
      "Salutation",
      "MaritalStatus",
      "Religion",
      "Caste",
      "CasteCategory",
      "MotherTongue",
      "Nationality",
      "BloodGroup",
      "EmployeeType",
      "EmployeeStatus",
      "EmployeeCategory",
      "Designation",
      "Department",
      "Grade",
      "SkillCategory",
      "ShiftGroup",
      "ReportingManagerMapping",
      "OfficeLocation",
      "HeadquarterLocation",
      "LocationType",
      "ProbationPolicy",
      "SeparationMode",
      "PositionChangeReason",
      "DocumentType",
      "DocumentSide",
      "Qualification",
      "EducationLevel",
      "EducationStatus",
      "Board",
      "Specialization",
      "EducationSpecialization",
      "StudyMode",
      "WorkExperienceRange",
      "RelevantExperienceRange",
      "LanguageProficiency",
      "ProficiencyLevel",
      "Language",
      "CertificationBody",
      "CertificationMaster",
      "EmployeeTag",
      "EmployeeNumberSeries",
      "SourceOfHire",
      "SourceOfHireType",
      "TransportType",
      "PayrollStatus",
      "PayrollMode",
      "PayrollGroup",
      "PolicyType",
      "InsuranceType",
      "CoverType",
      "PremiumFrequency",
      "InsuranceCompany",
      "NomineePurpose",
      "Relation",
      "Occupation",
      "Profession",
      "CommunicationChannel",
      "CommunicationTask",
      "EmployeeFilter",
      "ContractStatus",
      "VerificationStatus",
      "ResidentialStatus",
    ],
    {
      Gender: { formFields: labelBaseFields },
      Salutation: { formFields: labelBaseFields },
      MaritalStatus: { formFields: labelBaseFields },
      Religion: { formFields: labelBaseFields },
      Caste: { formFields: labelBaseFields },
      CasteCategory: { formFields: labelBaseFields },
      MotherTongue: { formFields: labelBaseFields },
      Nationality: { formFields: labelBaseFields },
      BloodGroup: { formFields: labelBaseFields },
      ReportingManagerMapping: {
        label: "Reporting Manager Mapping",
        companyScoped: true,
        formFields: [
          { key: "company", label: "Company", type: "select", relationMaster: "Company", required: true, section: "Company" },
          { key: "employee", label: "Manager Employee ID", type: "text", required: true, placeholder: "Enter employee id", section: "Manager" },
          { key: "designation", label: "Designation", type: "select", relationMaster: "Designation", section: "Manager" },
          { key: "department", label: "Department", type: "select", relationMaster: "Department", section: "Manager" },
          { key: "is_primary", label: "Primary Reporting Manager", type: "boolean", defaultValue: true, section: "Rules" },
          { key: "sort_order", label: "Sort Order", type: "number", defaultValue: 0, min: 0, section: "Rules" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          { key: "employee", label: "Employee", altKeys: ["employee_id", "employee_name", "manager_name"] },
          { key: "designation", label: "Designation", altKeys: ["designation_id", "designation_name"] },
          { key: "department", label: "Department", altKeys: ["department_id", "department_name"] },
          { key: "is_primary", label: "Primary", render: "boolean" },
          { key: "sort_order", label: "Sort Order" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      OfficeLocation: {
        label: "Office Location",
        formFields: [
          ...labelBaseFields,
          { key: "country", label: "Country", type: "select", relationMaster: "Country", required: true, section: "Address" },
          { key: "state", label: "State", type: "select", relationMaster: "State", required: true, section: "Address" },
          { key: "city", label: "City", type: "select", relationMaster: "City", required: true, section: "Address" },
          { key: "address_line1", label: "Address Line 1", type: "text", section: "Address" },
          { key: "address_line2", label: "Address Line 2", type: "text", section: "Address" },
          { key: "pincode", label: "Pincode", type: "text", section: "Address" },
          { key: "timezone", label: "Timezone", type: "text", defaultValue: "Asia/Kolkata", section: "Settings" },
          { key: "is_headquarter", label: "Headquarter", type: "boolean", defaultValue: false, section: "Settings" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Office Location", altKeys: ["name"] },
          { key: "city", label: "City", altKeys: ["city_name"] },
          { key: "state", label: "State", altKeys: ["state_name"] },
          { key: "country", label: "Country", altKeys: ["country_name"] },
          { key: "timezone", label: "Timezone" },
          { key: "is_headquarter", label: "HQ", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      HeadquarterLocation: {
        formFields: [
          ...labelBaseFields,
          { key: "country", label: "Country", type: "select", relationMaster: "Country", required: true, section: "Address" },
          { key: "state", label: "State", type: "select", relationMaster: "State", required: true, section: "Address" },
          { key: "city", label: "City", type: "select", relationMaster: "City", required: true, section: "Address" },
          { key: "address_line1", label: "Address Line 1", type: "text", section: "Address" },
          { key: "address_line2", label: "Address Line 2", type: "text", section: "Address" },
          { key: "pincode", label: "Pincode", type: "text", section: "Address" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Headquarter Location", altKeys: ["name"] },
          { key: "city", label: "City", altKeys: ["city_name"] },
          { key: "state", label: "State", altKeys: ["state_name"] },
          { key: "country", label: "Country", altKeys: ["country_name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Designation: {
        companyScoped: true,
        formFields: [
          { key: "company", label: "Company", type: "select", relationMaster: "Company", required: true, section: "Company" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter designation code", section: "Basic Details" },
          { key: "title", label: "Title", type: "text", required: true, placeholder: "Enter designation title", section: "Basic Details" },
          { key: "grade", label: "Grade", type: "select", relationMaster: "Grade", section: "Mapping" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "title", label: "Title", altKeys: ["label", "name"] },
          { key: "grade", label: "Grade", altKeys: ["grade_name", "grade_label"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Department: {
        companyScoped: true,
        parentFieldKey: "parent_department",
        formFields: [
          { key: "company", label: "Company", type: "select", relationMaster: "Company", required: true, section: "Company" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter department code", section: "Basic Details" },
          { key: "name", label: "Name", type: "text", required: true, placeholder: "Enter department name", section: "Basic Details" },
          { key: "parent_department", label: "Parent Department", type: "select", relationMaster: "Department", section: "Hierarchy" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "parent_department", label: "Parent Department", altKeys: ["parent_department_name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Grade: {
        companyScoped: true,
        formFields: [
          { key: "company_id", label: "Company", type: "select", relationMaster: "Company", required: true, section: "Company" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "L1 / L2 / SENIOR", section: "Basic Details" },
          { key: "label", label: "Label", type: "text", required: true, placeholder: "Enter grade label", section: "Basic Details" },
          { key: "level_number", label: "Level Number", type: "number", min: 1, section: "Ordering" },
          { key: "seniority_level", label: "Seniority Level", type: "text", placeholder: "Junior / Mid / Senior / Lead", section: "Classification" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label / Name", altKeys: ["name"] },
          { key: "level_number", label: "Level" },
          { key: "seniority_level", label: "Seniority" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      ShiftGroup: {
        label: "Shift Group",
        companyScoped: true,
        formFields: [
          { key: "company_id", label: "Company", type: "select", relationMaster: "Company", required: true, section: "Company" },
          { key: "shift_type_id", label: "Shift Type", type: "select", relationMaster: "ShiftType", section: "Shift Type" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "GEN / DAY / NITE", section: "Basic Details" },
          { key: "name", label: "Name", type: "text", required: true, placeholder: "Enter shift name", section: "Basic Details" },
          { key: "start_time", label: "Start Time", type: "time", required: true, section: "Timing" },
          { key: "end_time", label: "End Time", type: "time", required: true, section: "Timing" },
          { key: "grace_in_minutes", label: "Grace In Minutes", type: "number", defaultValue: 0, min: 0, section: "Timing" },
          { key: "grace_out_minutes", label: "Grace Out Minutes", type: "number", defaultValue: 0, min: 0, section: "Timing" },
          { key: "break_minutes", label: "Break Minutes", type: "number", defaultValue: 60, min: 0, section: "Timing" },
          { key: "weekly_off_days", label: "Weekly Off Days", type: "text", placeholder: "SAT,SUN", section: "Weekly Off" },
          { key: "is_overnight", label: "Overnight Shift", type: "boolean", defaultValue: false, section: "Rules" },
          { key: "is_flexible", label: "Flexible Shift", type: "boolean", defaultValue: false, section: "Rules" },
          { key: "ot_applicable", label: "OT Applicable", type: "boolean", defaultValue: true, section: "Rules" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "shift_type_id", label: "Shift Type", altKeys: ["shift_type_name", "shift_type"] },
          { key: "start_time", label: "Start" },
          { key: "end_time", label: "End" },
          { key: "weekly_off_days", label: "Weekly Off" },
          { key: "ot_applicable", label: "OT", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Qualification: { label: "Education Qualification" },
      Board: {
        formFields: [
          ...labelBaseFields,
          { key: "board_type", label: "Board Type", type: "select", options: boardTypeOptions, required: true, section: "Classification" },
          { key: "country_id", label: "Country", type: "select", relationMaster: "Country", section: "Classification" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label / Name", altKeys: ["name"] },
          { key: "board_type", label: "Board Type" },
          { key: "country_id", label: "Country", altKeys: ["country_name", "country"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Specialization: {
        formFields: [
          ...labelBaseFields,
          { key: "category", label: "Category", type: "text", placeholder: "Engineering / Management", section: "Classification" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label / Name", altKeys: ["name"] },
          { key: "category", label: "Category" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      EducationSpecialization: {
        formFields: [
          { key: "education_level_id", label: "Education Level", type: "select", relationMaster: "EducationLevel", required: true, section: "Education Level" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter specialization code", section: "Basic Details" },
          { key: "label", label: "Label", type: "text", required: true, placeholder: "Enter specialization name", section: "Basic Details" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label / Name", altKeys: ["name"] },
          { key: "education_level_id", label: "Education Level", altKeys: ["education_level_name", "education_level"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Language: {
        formFields: [
          ...labelBaseFields,
          { key: "iso_639_2_code", label: "ISO 639-2 Code", type: "text", required: true, placeholder: "eng", section: "Language Code" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Language", altKeys: ["name"] },
          { key: "iso_639_2_code", label: "ISO 639-2" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      LanguageProficiency: {
        formFields: [
          ...labelBaseFields,
          { key: "level_order", label: "Level Order", type: "number", required: true, min: 1, max: 10, section: "Ordering" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "level_order", label: "Level Order" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      ProficiencyLevel: { formFields: labelBaseFields },
      NomineePurpose: { formFields: labelBaseFields },
      Relation: {
        formFields: [
          ...labelBaseFields,
          { key: "is_dependent", label: "Dependent Relation", type: "boolean", defaultValue: false, section: "Rules" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Relation", altKeys: ["name"] },
          { key: "is_dependent", label: "Dependent", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Occupation: { formFields: labelBaseFields },
      Profession: { formFields: labelBaseFields },
      CommunicationChannel: { formFields: labelBaseFields },
      CommunicationTask: { formFields: labelBaseFields },
      DocumentType: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
          { key: "is_expiry_required", label: "Expiry Required", type: "boolean", defaultValue: false, section: "Rules" },
          { key: "is_number_required", label: "Number Required", type: "boolean", defaultValue: true, section: "Rules" },
          { key: "sides_required", label: "Sides Required", type: "select", options: documentSideOptions, section: "Rules" },
          { key: "max_attachments", label: "Max Attachments", type: "number", defaultValue: 2, min: 1, section: "Rules" },
          { key: "is_identity_verifiable", label: "Identity Verifiable", type: "boolean", defaultValue: false, section: "Identity Verification" },
          { key: "identity_code", label: "Identity Code", type: "text", section: "Identity Verification" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Document Type", altKeys: ["name"] },
          { key: "sides_required", label: "Sides" },
          { key: "max_attachments", label: "Max Files" },
          { key: "is_identity_verifiable", label: "Verifiable", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      DocumentSide: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
          { key: "is_mandatory", label: "Mandatory", type: "boolean", defaultValue: true, section: "Rules" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Document Side", altKeys: ["name"] },
          { key: "is_mandatory", label: "Mandatory", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      EmployeeType: { formFields: labelBaseFields },
      EmployeeCategory: { formFields: labelBaseFields },
      SourceOfHire: { formFields: labelBaseFields },
      SourceOfHireType: {
        formFields: [
          ...labelBaseFields,
          { key: "is_internal", label: "Internal Source", type: "boolean", defaultValue: false, section: "Classification" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "is_internal", label: "Internal", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      PayrollStatus: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "description", label: "Description" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      PayrollMode: { formFields: labelBaseFields },
      PayrollGroup: { formFields: labelBaseFields },
      TransportType: { formFields: labelBaseFields },
      PolicyType: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "description", label: "Description" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      InsuranceType: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
          { key: "is_group_policy", label: "Group Policy", type: "boolean", defaultValue: false, section: "Rules" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "is_group_policy", label: "Group Policy", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      CoverType: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
          { key: "is_family_based", label: "Family Based", type: "boolean", defaultValue: false, section: "Rules" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "is_family_based", label: "Family Based", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      PremiumFrequency: {
        formFields: [
          ...labelBaseFields,
          { key: "months_interval", label: "Months Interval", type: "number", required: true, min: 1, max: 12, section: "Frequency" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "months_interval", label: "Months Interval" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      InsuranceCompany: {
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
          { key: "irdai_code", label: "IRDAI Code", type: "text", section: "Regulatory" },
          { key: "registration_no", label: "Registration No", type: "text", section: "Regulatory" },
          { key: "country", label: "Country", type: "select", relationMaster: "Country", section: "Regulatory" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "irdai_code", label: "IRDAI Code" },
          { key: "registration_no", label: "Registration No" },
          { key: "country", label: "Country", altKeys: ["country_name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      EmployeeStatus: {
        label: "Employment Status",
        formFields: [
          ...labelBaseFields,
          { key: "is_terminal", label: "Terminal Status", type: "boolean", defaultValue: false, section: "Lifecycle" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "is_terminal", label: "Terminal", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      WorkExperienceRange: {
        label: "Experience Level",
        formFields: rangeBaseFields,
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "min_months", label: "Min Months" },
          { key: "max_months", label: "Max Months" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      RelevantExperienceRange: {
        formFields: rangeBaseFields,
        listColumns: [
          "code",
          { key: "label", label: "Label", altKeys: ["name"] },
          { key: "min_months", label: "Min Months" },
          { key: "max_months", label: "Max Months" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      CertificationMaster: { label: "Certification Masters" },
      SeparationMode: {
        label: "Exit Reason",
        formFields: [
          ...nameBaseFields,
          { key: "is_voluntary", label: "Voluntary", type: "boolean", defaultValue: false, section: "Flags" },
          { key: "is_terminal", label: "Terminal Status", type: "boolean", defaultValue: true, section: "Flags" },
          sortOrderField,
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "is_voluntary", label: "Voluntary", render: "boolean" },
          { key: "is_terminal", label: "Terminal", render: "boolean" },
          { key: "sort_order", label: "Sort Order" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      PositionChangeReason: {
        formFields: [
          ...nameBaseFields,
          {
            key: "change_type",
            label: "Change Type",
            type: "select",
            required: true,
            options: positionChangeTypeOptions,
            section: "Position Change",
          },
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "change_type", label: "Change Type" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      EmployeeFilter: {
        companyScoped: true,
        formFields: [
          ...companyNameBaseFields,
          {
            key: "filter_type",
            label: "Filter Type",
            type: "select",
            required: true,
            options: filterTypeOptions,
            section: "Filter Rules",
          },
          { key: "description", label: "Description", type: "textarea", section: "Filter Rules" },
          { key: "is_system", label: "System Filter", type: "boolean", defaultValue: false, section: "Flags" },
          { key: "member_count", label: "Member Count", type: "number", defaultValue: 0, min: 0, section: "Filter Rules" },
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "filter_type", label: "Filter Type" },
          { key: "member_count", label: "Members" },
          { key: "is_system", label: "System", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      ContractStatus: {
        formFields: [
          ...nameBaseFields,
          { key: "display_color", label: "Display Color", type: "color", section: "Display" },
          { key: "is_terminal", label: "Terminal Status", type: "boolean", defaultValue: false, section: "Flags" },
          sortOrderField,
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "display_color", label: "Color" },
          { key: "is_terminal", label: "Terminal", render: "boolean" },
          { key: "sort_order", label: "Sort Order" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      VerificationStatus: {
        formFields: [
          ...nameBaseFields,
          { key: "is_positive", label: "Positive Status", type: "boolean", defaultValue: false, section: "Flags" },
          { key: "is_terminal", label: "Terminal Status", type: "boolean", defaultValue: false, section: "Flags" },
          sortOrderField,
        ],
        listColumns: [
          "code",
          { key: "name", label: "Name", altKeys: ["label"] },
          { key: "is_positive", label: "Positive", render: "boolean" },
          { key: "is_terminal", label: "Terminal", render: "boolean" },
          { key: "sort_order", label: "Sort Order" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      ResidentialStatus: {
        formFields: [
          ...nameBaseFields,
          { key: "tax_regime_note", label: "Tax Regime Note", type: "textarea", section: "Tax" },
        ],
        listColumns: companyAuditColumns,
      },
    },
  ),
  makeCategory(
    "attendance",
    "Attendance Masters",
    [
      "Shift",
      "ShiftType",
      "ShiftRotation",
      "AttendanceStatus",
      "AttendanceScheme",
      "RegularizationReason",
      "PunchPolicy",
      "LateMarkRule",
      "EarlyExitRule",
      "OvertimePolicy",
      "BreakRule",
      "HolidayGroup",
      "WorkWeekPolicy",
      "BiometricDeviceMapping",
      "AttendancePolicy",
      "GeoFenceMaster",
      "WorkMode",
      "RosterTemplate",
      "CompOffPolicy",
      "AttendancePenaltyRule",
      "SwipeConfiguration",
    ],
    {
      Shift: { label: "Shift Master", ...companyScoped },
      ShiftType: companyScoped,
      RegularizationReason: { label: "Attendance Regularization Types" },
      OvertimePolicy: { label: "Overtime Rules" },
      CompOffPolicy: { label: "Comp Off Rules" },
      WorkWeekPolicy: { label: "Weekend Policy", ...companyScoped },
      HolidayGroup: companyScoped,
    },
  ),
  LEAVE_MASTER_CATEGORY,
  makeCategory(
    "payroll",
    "Payroll Masters",
    [
      "PayComponentGroup",
      "PayComponent",
      "Band",
      "TaxRegime",
      "ReimbursementType",
      "PfScheme",
      "EsiScheme",
      "BonusRule",
      "DeductionType",
      "LoanType",
      "PayrollCycle",
      "SalaryStructure",
      "SalaryStructureComponent",
      "Bank",
      "PayrollApprovalWorkflow",
      "TdsSection",
      "ArrearType",
      "StatutoryComponent",
      "PtStateSlab",
      "LwfSlab",
      "LabourRegisterType",
      "BankStatus",
      "AccountType",
      "PaymentType",
    ],
    {
      PayComponentGroup: {
        label: "Salary Components",
        formFields: [...BASE_FIELDS, { key: "is_earning", label: "Is Earning", type: "boolean" }],
      },
      PayComponent: {
        formFields: [...BASE_FIELDS, { key: "pay_component_group", label: "Component Group", type: "select", relationMaster: "PayComponentGroup" }],
      },
      Band: { label: "Pay Grades" },
      PfScheme: { label: "PF Settings" },
      EsiScheme: { label: "ESI Settings" },
      SalaryStructure: { label: "Salary Structures" },
      Bank: { label: "Bank Master" },
    },
  ),
  makeCategory(
    "organization",
    "Organization Masters",
    [
      "Company",
      "Branch",
      "BusinessUnit",
      "DepartmentDivision",
      "CostCenter",
      "ProfitCenter",
      "Region",
      "Zone",
      "Country",
      "State",
      "City",
      "ProductionCell",
      "Floor",
      "SeatingZone",
      "Extension",
      "Batch",
      "Cab",
    ],
    {
      Company: { formFields: COMPANY_EXTRA_FIELDS, listColumns: ["code", "label", "pan", "gstin"] },
      Branch: { companyScoped: true, formFields: BRANCH_FIELDS },
      BusinessUnit: companyScoped,
      DepartmentDivision: { label: "Division", ...companyScoped },
      CostCenter: companyScoped,
      ProfitCenter: companyScoped,
      State: {
        parentFieldKey: "country",
        formFields: [
          { key: "country", label: "Country", type: "select", relationMaster: "Country", required: true, section: "Location" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter state code", section: "Basic Details" },
          { key: "label", label: "State Name", type: "text", required: true, placeholder: "Enter state name", section: "Basic Details" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "State Name", altKeys: ["name"] },
          { key: "country", label: "Country", altKeys: ["country_name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      City: {
        parentFieldKey: "state",
        formFields: [
          { key: "state", label: "State", type: "select", relationMaster: "State", required: true, section: "Location" },
          { key: "code", label: "Code", type: "text", required: true, placeholder: "Enter city code", section: "Basic Details" },
          { key: "label", label: "City Name", type: "text", required: true, placeholder: "Enter city name", section: "Basic Details" },
          { key: "pincode", label: "Pincode", type: "text", placeholder: "Enter pincode", section: "Location" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "City Name", altKeys: ["name"] },
          { key: "state", label: "State", altKeys: ["state_name"] },
          { key: "pincode", label: "Pincode" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Country: {
        formFields: [
          { key: "code", label: "ISO Alpha-2 Code", type: "text", required: true, placeholder: "IN", section: "ISO Details" },
          { key: "iso3_code", label: "ISO Alpha-3 Code", type: "text", required: true, placeholder: "IND", section: "ISO Details" },
          { key: "numeric_code", label: "Numeric Code", type: "number", min: 1, section: "ISO Details" },
          { key: "label", label: "Country Name", type: "text", required: true, placeholder: "Enter country name", section: "Basic Details" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          "code",
          { key: "iso3_code", label: "ISO3" },
          { key: "numeric_code", label: "Numeric" },
          { key: "label", label: "Country Name", altKeys: ["name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      HeadquarterLocation: {
        formFields: [
          ...labelBaseFields,
          { key: "country", label: "Country", type: "select", relationMaster: "Country", required: true, section: "Address" },
          { key: "state", label: "State", type: "select", relationMaster: "State", required: true, section: "Address" },
          { key: "city", label: "City", type: "select", relationMaster: "City", required: true, section: "Address" },
          { key: "address_line1", label: "Address Line 1", type: "text", section: "Address" },
          { key: "address_line2", label: "Address Line 2", type: "text", section: "Address" },
          { key: "pincode", label: "Pincode", type: "text", section: "Address" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Location", altKeys: ["name"] },
          { key: "city", label: "City", altKeys: ["city_name"] },
          { key: "state", label: "State", altKeys: ["state_name"] },
          { key: "country", label: "Country", altKeys: ["country_name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      OfficeLocation: {
        label: "Work Location",
        formFields: [
          ...labelBaseFields,
          { key: "country", label: "Country", type: "select", relationMaster: "Country", required: true, section: "Address" },
          { key: "state", label: "State", type: "select", relationMaster: "State", required: true, section: "Address" },
          { key: "city", label: "City", type: "select", relationMaster: "City", required: true, section: "Address" },
          { key: "address_line1", label: "Address Line 1", type: "text", section: "Address" },
          { key: "address_line2", label: "Address Line 2", type: "text", section: "Address" },
          { key: "pincode", label: "Pincode", type: "text", section: "Address" },
          { key: "timezone", label: "Timezone", type: "text", defaultValue: "Asia/Kolkata", section: "Settings" },
          { key: "is_headquarter", label: "Headquarter", type: "boolean", defaultValue: false, section: "Settings" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Location", altKeys: ["name"] },
          { key: "city", label: "City", altKeys: ["city_name"] },
          { key: "timezone", label: "Timezone" },
          { key: "is_headquarter", label: "HQ", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      ProductionCell: {
        formFields: [
          ...labelBaseFields,
          { key: "office_location", label: "Office Location", type: "select", relationMaster: "OfficeLocation", required: true, section: "Mapping" },
          { key: "department", label: "Department", type: "select", relationMaster: "Department", section: "Mapping" },
          { key: "capacity", label: "Capacity", type: "number", min: 1, section: "Mapping" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Cell", altKeys: ["name"] },
          { key: "office_location", label: "Office Location", altKeys: ["office_location_name"] },
          { key: "department", label: "Department", altKeys: ["department_name"] },
          { key: "capacity", label: "Capacity" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Floor: {
        label: "Floor / Wing",
        formFields: [
          { key: "office_location", label: "Office Location", type: "select", relationMaster: "OfficeLocation", section: "Mapping" },
          { key: "floor_number", label: "Floor Number", type: "number", required: true, section: "Basic Details" },
          { key: "label", label: "Floor Label", type: "text", required: true, placeholder: "Enter floor label", section: "Basic Details" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          { key: "label", label: "Floor", altKeys: ["name"] },
          { key: "floor_number", label: "Floor Number" },
          { key: "office_location", label: "Office Location", altKeys: ["office_location_name"] },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      LocationType: { formFields: labelBaseFields },
    },
  ),
  makeCategory(
    "recruitment",
    "Recruitment Masters",
    [
      "JobFunction",
      "InterviewRound",
      "CandidateSource",
      "OfferStatus",
      "PipelineStage",
      "OfferTemplate",
      "InterviewPanel",
      "RejectionReason",
      "SkillAssessmentType",
      "JobLevel",
    ],
    {
      JobFunction: { label: "Job Role" },
      InterviewRound: { label: "Interview Type" },
      CandidateSource: { label: "Hiring Source" },
      OfferStatus: { label: "Candidate Status" },
      PipelineStage: { label: "Recruitment Stage" },
    },
  ),
  makeCategory(
    "performance",
    "Performance Masters",
    [
      "KpiLibrary",
      "GoalCategory",
      "AppraisalCycle",
      "CompetencyGroup",
      "Competency",
      "RatingScale",
      "FeedbackTemplate",
      "KraLibrary",
      "PerformanceBand",
    ],
    {
      KpiLibrary: { label: "KPI Templates" },
      AppraisalCycle: { label: "Review Cycles" },
      CompetencyGroup: { label: "Competency Types" },
    },
  ),
  makeCategory(
    "training-asset",
    "Training & Asset Masters",
    [
      "TrainingCategory",
      "TrainingMode",
      "TrainerType",
      "Course",
      "AssetCategory",
      "AssetCondition",
      "AssetType",
      "AssetStatus",
      "AssetAllocationType",
      "Vendor",
    ],
    {
      AssetCondition: { label: "Asset Status" },
      Vendor: { label: "Vendor Master" },
    },
  ),
  makeCategory(
    "workflow-security",
    "Workflow & Security Masters",
    [
      "WorkflowType",
      "SystemRole",
      "DefaultRole",
      "Permission",
      "NotificationTemplate",
      "EscalationType",
      "AuditEventType",
      "PasswordPolicy",
      "SessionPolicy",
      "NotificationChannel",
      "NotificationTrigger",
      "ApprovalAction",
      "MenuItem",
      "DataScopeType",
      "BulletinCategory",
      "PolicyCategory",
      "FormCategory",
      "ImportType",
      "LetterApprovalType",
      "ClearanceItemType",
      "CounterParty",
      "AuthorizedSignatory",
    ],
    {
      WorkflowType: { label: "Approval Workflow" },
      SystemRole: {
        label: "Role Master",
        formFields: [
          ...labelBaseFields,
          { key: "description", label: "Description", type: "textarea", section: "Details" },
        ],
        listColumns: [
          "code",
          { key: "label", label: "Role", altKeys: ["name"] },
          { key: "description", label: "Description" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      DefaultRole: {
        formFields: [
          { key: "role", label: "Role", type: "select", relationMaster: "SystemRole", required: true, section: "Role Mapping" },
          { key: "is_default", label: "Default Role", type: "boolean", defaultValue: true, section: "Role Mapping" },
          { key: "is_active", label: "Active", type: "boolean", section: "Status" },
        ],
        listColumns: [
          { key: "role", label: "Role", altKeys: ["role_name", "role_label"] },
          { key: "is_default", label: "Default", render: "boolean" },
          { key: "is_active", label: "Active", render: "status" },
        ],
      },
      Permission: { label: "Permission Groups" },
      EscalationType: { label: "Escalation Rules" },
      AuditEventType: { label: "Audit Categories" },
      PasswordPolicy: { label: "Access Policies" },
    },
  ),
];
