import type { HolidayAPI, LeaveApplicationAPI, LeaveBalanceAPI, LeaveTypeRef } from "./types";

export const DEMO_LEAVE_TYPES: LeaveTypeRef[] = [
  { id: "lt-1", name: "Privilege Leave", code: "PL", color_code: "#212529", is_paid: true },
  { id: "lt-2", name: "Sick Leave", code: "SL", color_code: "#495057", is_paid: true },
  { id: "lt-3", name: "Casual Leave", code: "CL", color_code: "#6C757D", is_paid: true },
  { id: "lt-4", name: "Loss of Pay", code: "LOP", color_code: "#ADB5BD", is_paid: false },
  { id: "lt-5", name: "Comp Off", code: "CO", color_code: "#495057", is_paid: true },
  { id: "lt-6", name: "Short Leave", code: "SHL", color_code: "#6C757D", is_paid: true },
  { id: "lt-7", name: "Out Duty", code: "OD", color_code: "#495057", is_paid: true },
  { id: "lt-8", name: "WFH", code: "WFH", color_code: "#343A40", is_paid: true },
  { id: "lt-9", name: "Gate Pass", code: "GP", color_code: "#868E96", is_paid: true },
  { id: "lt-10", name: "Overtime", code: "OT", color_code: "#212529", is_paid: true },
];

export const DEMO_BALANCES: LeaveBalanceAPI[] = [
  {
    id: "lb-1",
    employee_code: "EMP-0001",
    leave_type: "lt-1",
    leave_type_detail: DEMO_LEAVE_TYPES[0],
    period_start: "2026-01-01",
    period_end: "2026-12-31",
    opening_balance: 12,
    accrued: 2,
    used: 4,
    pending_approval: 1,
    carry_forwarded: 2,
    encashed: 0,
    available: 11,
    total_allocated: 14,
  },
  {
    id: "lb-2",
    employee_code: "EMP-0001",
    leave_type: "lt-2",
    leave_type_detail: DEMO_LEAVE_TYPES[1],
    period_start: "2026-01-01",
    period_end: "2026-12-31",
    opening_balance: 8,
    accrued: 0,
    used: 2,
    pending_approval: 0,
    carry_forwarded: 0,
    encashed: 0,
    available: 6,
    total_allocated: 8,
  },
  {
    id: "lb-3",
    employee_code: "EMP-0001",
    leave_type: "lt-3",
    leave_type_detail: DEMO_LEAVE_TYPES[2],
    period_start: "2026-01-01",
    period_end: "2026-12-31",
    opening_balance: 6,
    accrued: 0,
    used: 1,
    pending_approval: 0,
    carry_forwarded: 0,
    encashed: 0,
    available: 5,
    total_allocated: 6,
  },
];

export const DEMO_APPLICATIONS: LeaveApplicationAPI[] = [
  {
    id: "la-1",
    employee_code: "EMP-0002",
    employee_name: "Rohan Kulkarni",
    leave_type: "lt-2",
    leave_type_detail: DEMO_LEAVE_TYPES[1],
    from_date: "2026-04-16",
    to_date: "2026-04-16",
    from_half: "FULL",
    to_half: "FULL",
    total_days: 1,
    reason: "Fever and doctor consultation",
    status: "APPROVED",
    applied_on: "2026-04-14",
    approved_at: "2026-04-15T10:15:00Z",
  },
  {
    id: "la-2",
    employee_code: "EMP-0001",
    employee_name: "Arjun Sharma",
    leave_type: "lt-1",
    leave_type_detail: DEMO_LEAVE_TYPES[0],
    from_date: "2026-05-06",
    to_date: "2026-05-08",
    from_half: "FULL",
    to_half: "FULL",
    total_days: 3,
    reason: "Family function out of station",
    status: "SUBMITTED",
    applied_on: "2026-04-29",
    approved_at: null,
  },
];

export const DEMO_HOLIDAYS_2026: HolidayAPI[] = [
  { id: "h-2026-01-01", name: "New Year's Day", date: "2026-01-01", holiday_type: "National", is_optional: false },
  { id: "h-2026-01-26", name: "Republic Day", date: "2026-01-26", holiday_type: "National", is_optional: false },
  { id: "h-2026-03-08", name: "Holi", date: "2026-03-08", holiday_type: "Festival", is_optional: true },
  { id: "h-2026-03-29", name: "Good Friday", date: "2026-03-29", holiday_type: "Festival", is_optional: false },
  { id: "h-2026-05-01", name: "Maharashtra Day", date: "2026-05-01", holiday_type: "National", is_optional: false },
  { id: "h-2026-06-08", name: "Bakrid (Eid al-Adha)", date: "2026-06-08", holiday_type: "Festival", is_optional: true },
  { id: "h-2026-08-15", name: "Independence Day", date: "2026-08-15", holiday_type: "National", is_optional: false },
  { id: "h-2026-10-02", name: "Gandhi Jayanti", date: "2026-10-02", holiday_type: "National", is_optional: false },
  { id: "h-2026-10-20", name: "Diwali", date: "2026-10-20", holiday_type: "Festival", is_optional: true },
  { id: "h-2026-12-25", name: "Christmas", date: "2026-12-25", holiday_type: "Festival", is_optional: false },
];

