# Generated by Django 5.2.14 on 2026-05-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="from_session",
            field=models.CharField(
                choices=[("first_half", "First Half"), ("second_half", "Second Half")],
                default="first_half",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="to_session",
            field=models.CharField(
                choices=[("first_half", "First Half"), ("second_half", "Second Half")],
                default="first_half",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequestday",
            name="session",
            field=models.CharField(
                choices=[("first_half", "First Half"), ("second_half", "Second Half")],
                max_length=12,
            ),
        ),
    ]
