# Generated by Django 5.2.14 on 2026-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_alter_leaverequest_from_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
