# Generated by Django 5.2.14 on 2026-06-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('allowed_days', models.PositiveIntegerField()),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='leave.leavetype')),
            ],
            options={
                'db_table': 'mst_leave_mapping',
                'ordering': ['role', 'leave_type__name'],
                'unique_together': {('role', 'leave_type')},
            },
        ),
    ]
