# Generated by Django 5.2.14 on 2026-06-02 15:36
# Renamed from 0004_leavepolicy_location.py to resolve duplicate-0004 conflict.
# Fixed: original used default=timezone.now (a datetime) for an integer FK — changed to nullable.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0031_team_team_manager_and_more"),
        ("leave", "0004_leavemapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavepolicy",
            name="location",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_policies",
                to="employees.state",
            ),
        ),
    ]
