# Generated by Django 5.2.14 on 2026-06-04 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leavepolicy_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalworkflowconfig',
            options={'ordering': ['level']},
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowconfig',
            unique_together={('module', 'workflow_name')},
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='location',
        ),
        migrations.AddField(
            model_name='approvalworkflowconfig',
            name='approver_type',
            field=models.CharField(blank=True, choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('SPECIFIC_USER', 'Specific User'), ('HR', 'HR Department'), ('DEPARTMENT_HEAD', 'Department Head')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflowconfig',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_configs', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='approvalworkflowconfig',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Approval level (1 = first approver, 2 = second, …)', null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflowconfig',
            name='sla_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='approvalworkflowconfig',
            name='specific_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_workflow_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='actioned_on',
            field=models.DateTimeField(blank=True, help_text='Spec-mandated alias for actioned_at; populated when approval action is taken', null=True),
        ),
        migrations.AddField(
            model_name='leavebalanceledger',
            name='leave_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='leave.leavebalance'),
        ),
        migrations.AddField(
            model_name='leavebalanceledger',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='leave.leaverequest'),
        ),
        migrations.AddField(
            model_name='leavebalanceledger',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='allow_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='allow_negative_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='applicable_roles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='carry_forward_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='days_per_year',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='max_consecutive_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='min_notice_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_year',
            field=models.PositiveIntegerField(default=0, help_text='Calendar year of from_date; auto-populated on save'),
        ),
        migrations.AddField(
            model_name='leavestatushistory',
            name='new_status',
            field=models.CharField(default='', help_text='Spec-mandated alias for to_status', max_length=20),
        ),
        migrations.AddField(
            model_name='leavestatushistory',
            name='old_status',
            field=models.CharField(blank=True, help_text='Spec-mandated alias for from_status', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('delegated', 'Delegated'), ('skipped', 'Skipped'), ('auto_approved', 'Auto Approved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leavebalanceledger',
            name='transaction_type',
            field=models.CharField(choices=[('pending_application', 'Pending Application'), ('allocation', 'Allocation'), ('opening_balance', 'Opening Balance'), ('accrual', 'Accrual'), ('usage', 'Usage'), ('carry_forward', 'Carry Forward'), ('encashment', 'Encashment'), ('lapse', 'Lapse'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowconfig',
            unique_together={('leave_type', 'level'), ('module', 'workflow_name')},
        ),
        migrations.AddIndex(
            model_name='approvalworkflowconfig',
            index=models.Index(fields=['leave_type'], name='approval_wo_leave_t_1b0f06_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowconfig',
            index=models.Index(fields=['level'], name='approval_wo_level_adec17_idx'),
        ),
    ]
