# Generated by Django 5.2.14 on 2026-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0006_alter_approvalworkflowconfig_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
