"""Education Details UI — field sets (employee module screenshot)."""

EDUCATION_ROW_FIELDS = (
    "id",
    "qualification_id",
    "qualification",
    "specialization_id",
    "specialization",
    "institution_id",
    "institution",
    "institution_name",
    "university_id",
    "university",
    "year_of_passing_id",
    "year_of_passing",
    "yearOfPassing",
    "from_date",
    "to_date",
    "start_date",
    "end_date",
    "percentage_or_cgpa",
    "grade",
    "degree_certificate_url",
    "marksheet_url",
    "leaving_certificate_url",
)

EDUCATION_ROW_EDITABLE = frozenset({
    "id",
    "qualification_id",
    "qualification",
    "specialization_id",
    "specialization",
    "institution_id",
    "institution",
    "institution_name",
    "university_id",
    "university",
    "year_of_passing_id",
    "year_of_passing",
    "yearOfPassing",
    "from_date",
    "to_date",
    "start_date",
    "end_date",
    "percentage_or_cgpa",
    "grade",
    "degree_certificate_url",
    "marksheet_url",
    "leaving_certificate_url",
    "remove",
    "delete",
})
