"""Family Details UI — field sets (employee module screenshot)."""

FAMILY_MEMBER_ROW_FIELDS = (
    "id",
    "name",
    "first_name",
    "last_name",
    "relation_id",
    "relation",
    "relationship_id",
    "relationship",
    "date_of_birth",
    "age",
    "age_years",
    "gender_id",
    "gender",
    "blood_group_id",
    "blood_group",
    "phone",
    "mobile_no",
    "occupation_id",
    "occupation",
    "is_dependent",
    "isDependent",
    "is_emergency_contact",
    "emergency_contact",
)

FAMILY_MEMBER_EDITABLE = frozenset({
    "id",
    "name",
    "first_name",
    "last_name",
    "relation_id",
    "relationship_id",
    "date_of_birth",
    "gender_id",
    "blood_group_id",
    "phone",
    "mobile_no",
    "occupation_id",
    "is_dependent",
    "isDependent",
    "is_emergency_contact",
    "emergency_contact",
    "remove",
    "delete",
})
