"""Personal Details UI — field sets (employee module screenshot)."""

PERSONAL_DETAILS_FIELDS = (
    "first_name",
    "middle_name",
    "last_name",
    "father_name",
    "spouse_name",
    "date_of_birth",
    "actual_dob",
    "actual_date_of_birth",
    "place_of_birth",
    "gender_id",
    "gender",
    "marital_status_id",
    "marital_status",
    "blood_group_id",
    "blood_group",
    "nationality_id",
    "nationality",
    "religion_id",
    "religion",
    "caste_id",
    "caste",
    "caste_category_id",
    "caste_category",
    "identification_mark",
    "height",
    "height_cm",
    "weight",
    "weight_kg",
    "is_physically_challenged",
    "is_international_employee",
    "joining_date",
)

# Stored in change request request_data (no display-only keys)
PERSONAL_DETAILS_EMPLOYEE_EDITABLE = frozenset({
    "first_name",
    "middle_name",
    "last_name",
    "date_of_birth",
    "actual_dob",
    "actual_date_of_birth",
    "joining_date",
    "gender_id",
    "marital_status_id",
    "religion_id",
    "caste_category_id",
    "place_of_birth",
    "is_physically_challenged",
    "father_name",
    "spouse_name",
    "blood_group_id",
    "nationality_id",
    "caste_id",
    "identification_mark",
    "height",
    "height_cm",
    "weight",
    "weight_kg",
    "is_international_employee",
})
