# Generated by Django 5.2.14 on 2026-05-29 11:38

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.TextField(blank=True)),
                ("login_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(db_index=True, default=False)),
                ("revoked_reason", models.CharField(blank=True, max_length=200)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_sessions",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Session",
                "verbose_name_plural": "HR Sessions",
                "db_table": "hr_session",
            },
        ),
        migrations.CreateModel(
            name="HRAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=50)),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model / table name, e.g. Employee or leave_application",
                        max_length=100,
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        db_column="actor_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs_as_actor",
                        to="employees.employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="employees.company",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="security.hrsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "hr_audit_log",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="IPWhitelist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "ip_cidr",
                    models.CharField(
                        help_text="CIDR notation, e.g. 192.168.1.0/24", max_length=50
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_whitelists",
                        to="employees.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_whitelists",
                        to="employees.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Whitelist",
                "verbose_name_plural": "IP Whitelists",
                "db_table": "sec_ip_whitelist",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("label", models.CharField(max_length=150)),
                ("route_path", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="security.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "db_table": "sec_menu_item",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        help_text="Module name: EMPLOYEE / LEAVE / ATTENDANCE / PAYROLL / etc.",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action: view / create / edit / delete / approve / export / import",
                        max_length=50,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="Resource name, e.g. leave_application",
                        max_length=100,
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-notation code, e.g. leave.approve_leave",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "mst_permission",
                "indexes": [
                    models.Index(
                        fields=["module", "action"], name="idx_sec_perm_module_action"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permissions",
                        to="security.permission",
                    ),
                ),
            ],
            options={
                "db_table": "sec_group_permission",
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("group_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        through="security.GroupPermission",
                        to="security.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
                "db_table": "sec_permission_group",
            },
        ),
        migrations.AddField(
            model_name="grouppermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_permissions",
                to="security.permissiongroup",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "access_level",
                    models.CharField(default="SELF_SERVICE", max_length=30),
                ),
                ("is_custom", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "System Role",
                "verbose_name_plural": "System Roles",
                "db_table": "mst_system_role",
                "indexes": [
                    models.Index(fields=["code"], name="idx_mst_system_role_code")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="uq_mst_system_role_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRoleAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="NULL = indefinite", null=True
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_role_assignments",
                        to="employees.employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emp_role_assignments",
                        to="employees.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="department_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_role_assignments",
                        to="employees.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="employees.employee",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="revoked_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_role_assignments",
                        to="employees.employee",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emp_role_assignments",
                        to="security.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Role Assignment",
                "verbose_name_plural": "Employee Role Assignments",
                "db_table": "employee_role_assignments",
            },
        ),
        migrations.CreateModel(
            name="DataScopeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module code, e.g. LEAVE / ATTENDANCE / EMPLOYEE",
                        max_length=50,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All (company-wide)"),
                            ("REPORTEES", "Own reportees"),
                            ("DEPT", "Own department"),
                            ("BRANCH", "Own branch"),
                            ("SELF", "Self only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope_entity_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Explicit entity UUIDs for DEPT / BRANCH scopes (optional override).",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_scope_rules",
                        to="security.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Scope Rule",
                "verbose_name_plural": "Data Scope Rules",
                "db_table": "sec_data_scope_rule",
            },
        ),
        migrations.CreateModel(
            name="ColumnRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("column_name", models.CharField(max_length=100)),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("HIDE", "Hidden"),
                            ("MASK", "Masked"),
                            ("READ_ONLY", "Read-only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_restrictions",
                        to="security.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column Restriction",
                "verbose_name_plural": "Column Restrictions",
                "db_table": "sec_column_restriction",
            },
        ),
        migrations.CreateModel(
            name="RoleMenuPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_export", models.BooleanField(default=False)),
                ("can_import", models.BooleanField(default=False)),
                ("can_approve", models.BooleanField(default=False)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="security.menuitem",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_permissions",
                        to="security.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Menu Permission",
                "verbose_name_plural": "Role Menu Permissions",
                "db_table": "sec_role_menu_permission",
            },
        ),
        migrations.CreateModel(
            name="RolePermissionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permission_groups",
                        to="security.permissiongroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permission_groups",
                        to="security.role",
                    ),
                ),
            ],
            options={
                "db_table": "sec_role_permission_group",
            },
        ),
        migrations.AddIndex(
            model_name="hrsession",
            index=models.Index(
                fields=["employee", "is_revoked"], name="idx_hr_session_emp_revoked"
            ),
        ),
        migrations.AddIndex(
            model_name="hrauditlog",
            index=models.Index(
                fields=["company", "module", "changed_at"],
                name="idx_hr_audit_co_mod_dt",
            ),
        ),
        migrations.AddIndex(
            model_name="hrauditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="idx_hr_audit_entity"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppermission",
            unique_together={("group", "permission")},
        ),
        migrations.AddIndex(
            model_name="employeeroleassignment",
            index=models.Index(
                fields=["employee", "role", "is_active"], name="idx_emp_rola_emp_role"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeroleassignment",
            index=models.Index(fields=["company", "role"], name="idx_emp_rola_co_role"),
        ),
        migrations.AlterUniqueTogether(
            name="datascoperule",
            unique_together={("role", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="columnrestriction",
            unique_together={("role", "table_name", "column_name")},
        ),
        migrations.AlterUniqueTogether(
            name="rolemenupermission",
            unique_together={("role", "menu_item")},
        ),
        migrations.AlterUniqueTogether(
            name="rolepermissiongroup",
            unique_together={("role", "group")},
        ),
    

]


    
