# Generated by Django 5.2.14 on 2026-05-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="employeeroleassignment",
            name="idx_emp_rola_co_role",
        ),
        migrations.RemoveField(
            model_name="employeeroleassignment",
            name="company",
        ),
    ]
