# Generated by Django 5.2.14 on 2026-06-02 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdefinition',
            name='break_mins',
            field=models.PositiveIntegerField(default=75, help_text='Default unpaid break deducted when no lunch punches are available.'),
        ),
        migrations.CreateModel(
            name='AttendanceTrackingMode',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict, null=True)),
                ('meta_version', models.IntegerField(default=1)),
                ('created_by_system', models.CharField(blank=True, default='SYSTEM', max_length=50, null=True)),
                ('updated_by_system', models.CharField(blank=True, default='SYSTEM', max_length=50, null=True)),
                ('created_source', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_source', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('extra_attributes', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Tracking Mode',
                'verbose_name_plural': 'Attendance Tracking Modes',
                'db_table': 'mst_attendance_tracking_mode',
                'indexes': [models.Index(fields=['code'], name='idx_mst_tracking_mode_code')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_mst_tracking_mode_code')],
            },
        ),
    ]
