# Generated by Django 5.2.14 on 2026-06-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_shiftdefinition_break_mins"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyattendance",
            options={"ordering": ["-attendance_date"]},
        ),
    ]
