# Generated by Django 5.2.14 on 2026-06-02 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_institution_big_auto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOffDays',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('day_number', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict, null=True)),
                ('meta_version', models.IntegerField(default=1)),
                ('created_by_system', models.CharField(blank=True, default='SYSTEM', max_length=50, null=True)),
                ('updated_by_system', models.CharField(blank=True, default='SYSTEM', max_length=50, null=True)),
                ('created_source', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_source', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('extra_attributes', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Weekly Off Day',
                'verbose_name_plural': 'Weekly Off Days',
                'db_table': 'mst_weekly_off_days',
                'indexes': [models.Index(fields=['code'], name='idx_mst_weekly_off_days_code'), models.Index(fields=['day_number'], name='idx_mst_weekly_off_days_day')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_mst_weekly_off_days_code')],
            },
        ),
    ]
