# Generated by Django 5.2.14

from django.db import migrations


def seed_weekly_off_days(apps, schema_editor):
    """Seed weekly off days master with all 7 days of the week."""
    WeeklyOffDays = apps.get_model('employees', 'WeeklyOffDays')
    
    weekly_days = [
        {"code": "MON", "label": "Monday", "day_number": 0},
        {"code": "TUE", "label": "Tuesday", "day_number": 1},
        {"code": "WED", "label": "Wednesday", "day_number": 2},
        {"code": "THU", "label": "Thursday", "day_number": 3},
        {"code": "FRI", "label": "Friday", "day_number": 4},
        {"code": "SAT", "label": "Saturday", "day_number": 5},
        {"code": "SUN", "label": "Sunday", "day_number": 6},
    ]
    
    for day in weekly_days:
        WeeklyOffDays.objects.get_or_create(
            code=day["code"],
            defaults={
                "label": day["label"],
                "day_number": day["day_number"],
                "is_active": True
            }
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded weekly off days."""
    WeeklyOffDays = apps.get_model('employees', 'WeeklyOffDays')
    codes = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
    WeeklyOffDays.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_add_weekly_off_days'),
    ]

    operations = [
        migrations.RunPython(seed_weekly_off_days, reverse_seed),
    ]
