# Generated by Django 5.2.14 on 2026-06-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0030_seed_weekly_off_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_manager",
            field=models.ForeignKey(
                blank=True,
                db_column="team_manager_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_teams",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeeemploymentdetails",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_column="team_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emp_employment_details",
                to="employees.team",
            ),
        ),
    ]
